[tool.poetry]
name = "shikanoko-markov"
version = "0.1.0"
description = ""
authors = ["ARGI-BERRI <me@endroit.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tqdm = "^4.66.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
